### ISSUE TITLE
Negative Votes Needed?

### ISSUE THREAD

**Issue by arnavravinder** [hackclub/high-seas#763]
For some people, they requite negative votes before they can get their doubloon payout. This has occurred for quite a few users atm, and I/Support Team don't really know how to rectify this?

![Image](https://github.com/user-attachments/assets/25faed97-7561-4897-ae50-b64064d617ed)
![Image](https://github.com/user-attachments/assets/6e9791eb-7ad8-4ffc-be37-d5882138b8b8)
![Image](https://github.com/user-attachments/assets/e5901716-5ea0-4f72-a336-2fd85de68a39)

cc @polytroper

**Comment by NeonGamerBot-QK** [comment]
This is when you have faulty / fraud votes or projects so they are reversed votes and will go into negatives. You can get them out of the negatives by voting the required amount

**Comment by YetAnotherNotHacking** [comment]
![Image](https://github.com/user-attachments/assets/da80111b-1574-43dd-b584-789d8fc12112)

do I need to vote 91 times then? the time is 0, it looks like in their image the time is also very low, is this the issue?

**Comment by YetAnotherNotHacking** [comment]
possible a project should have atleast 30 minutes or so? I am not sure what is causing this. I would be happy to look into this and submit a path, but only if that is wanted/needed.

This looks like not "fraud" here but "fault". I think that it should be atleast less confusing. Maybe an error message than a confusing negative vote count.

**Comment by NeonGamerBot-QK** [comment]
> ![Image](https://github.com/user-attachments/assets/da80111b-1574-43dd-b584-789d8fc12112)
> 
> do I need to vote 91 times then? the time is 0, it looks like in their image the time is also very low, is this the issue?

yes you will have to vote 91 times + current vote rate (15 iirc) 
(not 100% certain, but thats what i have done)

**Comment by NeonGamerBot-QK** [comment]
> possible a project should have atleast 30 minutes or so? I am not sure what is causing this. I would be happy to look into this and submit a path, but only if that is wanted/needed.
> 
> This looks like not "fraud" here but "fault". I think that it should be atleast less confusing. Maybe an error message than a confusing negative vote count.

Please link this in the slack!! (post in #high-seas-help)

**Comment by YetAnotherNotHacking** [comment]
... I really need to vote 91 times? what did I do wrong :c

**Comment by NeonGamerBot-QK** [comment]
not you. your project will need 100 votes (rounded) to get a payout..
if you have the pirates curse this can be from low quality votes.

**Comment by YetAnotherNotHacking** [comment]
how can I check if I have the pirates curse?

**Comment by NeonGamerBot-QK** [comment]
you should have gotten a DM, if u dont have one ur good.

**Comment by YetAnotherNotHacking** [comment]
No dm, what else might cause it?

**Comment by NeonGamerBot-QK** [comment]
not sure tbh.
cc @maxwofford

**Comment by polytroper** [comment]
@YetAnotherNotHacking @NeonGamerBot-QK no that is not the issue. It is talking about votes required from other users, not votes you need to do yourself. I am looking into it rn

**Comment by YetAnotherNotHacking** [comment]
![Image](https://github.com/user-attachments/assets/6ebf7004-0dd1-4734-b381-f32ef21544cd)
:) it is working

**Comment by YetAnotherNotHacking** [comment]
this is resolved, should be marked as such!

**Comment by polytroper** [comment]
Fixed

**Comment by arnavravinder** [comment]
This is still occurring for users, is there a fix out?
![Image](https://github.com/user-attachments/assets/a89332cb-aa23-4ec3-bc40-ce206adf3201)
https://hackclub.slack.com/archives/C07Q1Q76BGV/p1732080125642159

**Comment by YetAnotherNotHacking** [comment]
was it made not possible to submit a project under 1 hour? that seemed to be the cause. I believe that there is another issue about this.

**Comment by polytroper** [comment]
Pretty sure this is fixed

**Comment by polytroper** [comment]
Wait no I just read the comment chain… apparently not fixed?

**Comment by arnavravinder** [comment]
I haven't seen any of these issues in the past 10 days or so, seems fine
